--------------------------------------------------------
--  File created - Saturday-July-04-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_INVENTORY_ID
--------------------------------------------------------

   CREATE SEQUENCE  "INVENTORY_USER"."SEQ_INVENTORY_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRODUCT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "INVENTORY_USER"."SEQ_PRODUCT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RESERVATION_ID
--------------------------------------------------------

   CREATE SEQUENCE  "INVENTORY_USER"."SEQ_RESERVATION_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 59 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table INVENTORY
--------------------------------------------------------

  CREATE TABLE "INVENTORY_USER"."INVENTORY" 
   (	"INVENTORY_ID" VARCHAR2(20 BYTE), 
	"PRODUCT_ID" VARCHAR2(20 BYTE), 
	"QUANTITY" NUMBER(10,0), 
	"WAREHOUSE" VARCHAR2(50 BYTE) DEFAULT 'WAREHOUSE-1', 
	"LAST_UPDATED" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INVENTORY_RESERVATIONS
--------------------------------------------------------

  CREATE TABLE "INVENTORY_USER"."INVENTORY_RESERVATIONS" 
   (	"RESERVATION_ID" VARCHAR2(20 BYTE), 
	"ORDER_ID" VARCHAR2(20 BYTE), 
	"PRODUCT_ID" VARCHAR2(20 BYTE), 
	"QUANTITY" NUMBER(10,0), 
	"RESERVED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'RESERVED'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "INVENTORY_USER"."PRODUCTS" 
   (	"PRODUCT_ID" VARCHAR2(20 BYTE), 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"UNIT_PRICE" NUMBER(10,2), 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View VW_AVAILABLE_INVENTORY
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "INVENTORY_USER"."VW_AVAILABLE_INVENTORY" ("PRODUCT_ID", "PRODUCT_NAME", "UNIT_PRICE", "CATEGORY", "INVENTORY_ID", "TOTAL_QUANTITY", "WAREHOUSE", "RESERVED_QUANTITY", "AVAILABLE_QUANTITY") AS 
  SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.UNIT_PRICE,
    p.CATEGORY,
    i.INVENTORY_ID,
    i.QUANTITY                            AS TOTAL_QUANTITY,
    i.WAREHOUSE,
    COALESCE(r.RESERVED_QTY, 0)          AS RESERVED_QUANTITY,
    i.QUANTITY - COALESCE(r.RESERVED_QTY, 0) AS AVAILABLE_QUANTITY
FROM
    PRODUCTS p
    JOIN INVENTORY i ON p.PRODUCT_ID = i.PRODUCT_ID
    LEFT JOIN (
        SELECT PRODUCT_ID, SUM(QUANTITY) AS RESERVED_QTY
        FROM INVENTORY_RESERVATIONS
        WHERE STATUS = 'RESERVED'
        GROUP BY PRODUCT_ID
    ) r ON p.PRODUCT_ID = r.PRODUCT_ID
;
REM INSERTING into INVENTORY_USER.INVENTORY
SET DEFINE OFF;
Insert into INVENTORY_USER.INVENTORY (INVENTORY_ID,PRODUCT_ID,QUANTITY,WAREHOUSE,LAST_UPDATED) values ('INV-001','PROD-A1',50,'WAREHOUSE-1',to_timestamp('23-JUN-26 10.36.47.047000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INVENTORY_USER.INVENTORY (INVENTORY_ID,PRODUCT_ID,QUANTITY,WAREHOUSE,LAST_UPDATED) values ('INV-002','PROD-B2',200,'WAREHOUSE-1',to_timestamp('23-JUN-26 10.36.47.052000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INVENTORY_USER.INVENTORY (INVENTORY_ID,PRODUCT_ID,QUANTITY,WAREHOUSE,LAST_UPDATED) values ('INV-003','PROD-C3',75,'WAREHOUSE-1',to_timestamp('23-JUN-26 10.36.47.055000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INVENTORY_USER.INVENTORY (INVENTORY_ID,PRODUCT_ID,QUANTITY,WAREHOUSE,LAST_UPDATED) values ('INV-004','PROD-D4',2,'WAREHOUSE-1',to_timestamp('23-JUN-26 10.36.47.060000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into INVENTORY_USER.INVENTORY_RESERVATIONS
SET DEFINE OFF;
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-1','ORD-001','PROD-A1',1,to_timestamp('27-JUN-26 06.16.29.684000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-2','ORD-001','PROD-A1',1,to_timestamp('27-JUN-26 06.18.48.701000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-3','ORD-001','PROD-A1',1,to_timestamp('27-JUN-26 06.36.55.587000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-4','ORD-001','PROD-A1',1,to_timestamp('27-JUN-26 06.37.28.592000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-5','ORD-001','PROD-A1',1,to_timestamp('27-JUN-26 07.08.29.914000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-7','ORD-009','PROD-D4',1,to_timestamp('29-JUN-26 11.22.41.947000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-8','ORD-010','PROD-A1',1,to_timestamp('30-JUN-26 04.12.30.267000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-9','ORD-011','PROD-A1',1,to_timestamp('30-JUN-26 04.32.07.662000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-10','ORD-011','PROD-A1',1,to_timestamp('30-JUN-26 04.32.50.451000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-11','ORD-011','PROD-A1',1,to_timestamp('30-JUN-26 04.33.43.813000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-12','ORD-011','PROD-A1',1,to_timestamp('30-JUN-26 04.34.13.540000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-13','ORD-011','PROD-A1',1,to_timestamp('30-JUN-26 04.35.12.684000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-14','ORD-011','PROD-A1',1,to_timestamp('30-JUN-26 04.36.18.886000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-15','ORD-011','PROD-A1',1,to_timestamp('30-JUN-26 05.18.07.706000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-16','ORD_001','PROD-A1',2,to_timestamp('30-JUN-26 08.04.34.514000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-17','ORD_001','PROD-B2',1,to_timestamp('30-JUN-26 08.05.40.337000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-18','ORD_001','PROD-B2',1,to_timestamp('30-JUN-26 08.06.54.887000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-19','ORD-015','PROD-A1',1,to_timestamp('30-JUN-26 11.31.42.576000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-20','ORD-015','PROD-A1',1,to_timestamp('30-JUN-26 11.32.57.117000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-21','ORD-015','PROD-A1',1,to_timestamp('30-JUN-26 11.33.27.659000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-22','ORD-015','PROD-A1',1,to_timestamp('30-JUN-26 11.34.10.008000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-23','ORD-015','PROD-A1',1,to_timestamp('30-JUN-26 11.36.01.242000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-24','ORD-015','PROD-A1',1,to_timestamp('01-JUL-26 07.41.46.259000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-25','ORD-015','PROD-B2',1,to_timestamp('02-JUL-26 04.08.59.609000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-26','ORD-016','PROD-A1',1,to_timestamp('02-JUL-26 04.09.58.510000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-27','ORD-015','PROD-B2',1,to_timestamp('02-JUL-26 04.11.05.505000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-28','ORD-015','PROD-B2',1,to_timestamp('02-JUL-26 04.41.26.684000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-29','ORD-015','PROD-B2',1,to_timestamp('02-JUL-26 06.08.16.642000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-30','ORD-015','PROD-B2',1,to_timestamp('02-JUL-26 06.10.08.608000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-31','ORD-015','PROD-B2',1,to_timestamp('02-JUL-26 07.23.24.483000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-32','ORD-015','PROD-B2',1,to_timestamp('02-JUL-26 07.24.02.910000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-33','ORD-015','PROD-B2',1,to_timestamp('02-JUL-26 07.24.47.585000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-34','ORD-015','PROD-B2',1,to_timestamp('02-JUL-26 07.25.31.634000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-35','ORD-015','PROD-B2',1,to_timestamp('02-JUL-26 07.26.21.145000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-36','ORD_001','PROD-C3',1,to_timestamp('02-JUL-26 07.35.37.415000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-37','ORD_001','PROD-C3',1,to_timestamp('02-JUL-26 07.40.23.387000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-38','ORD_001','PROD-C3',1,to_timestamp('02-JUL-26 07.57.20.487000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-39','ORD-001','PROD-A1',10,to_timestamp('02-JUL-26 08.20.29.754000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-40','ORD-001','PROD-A1',10,to_timestamp('02-JUL-26 08.23.04.829000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-41','ORD-001','PROD-A1',1,to_timestamp('02-JUL-26 08.56.06.575000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-42','ORD-001','PROD-B2',2,to_timestamp('02-JUL-26 08.56.06.592000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-43','ORD-001','PROD-B2',2,to_timestamp('02-JUL-26 08.56.58.784000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-44','ORD-001','PROD-A1',1,to_timestamp('02-JUL-26 09.07.14.644000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-45','ORD-001','PROD-B2',2,to_timestamp('02-JUL-26 09.07.14.657000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-46','ORD-001','PROD-A1',1,to_timestamp('02-JUL-26 09.10.01.041000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-47','ORD-001','PROD-B2',2,to_timestamp('02-JUL-26 09.10.01.078000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-48','ORD_001','PROD-C3',1,to_timestamp('02-JUL-26 09.10.44.931000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-49','ORD_001','PROD-C3',1,to_timestamp('02-JUL-26 09.10.44.940000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-50','ORD_001','PROD-C3',1,to_timestamp('02-JUL-26 09.12.30.237000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-51','ORD_001','PROD-C3',1,to_timestamp('02-JUL-26 09.12.30.247000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-52','ORD-001','PROD-A1',1,to_timestamp('02-JUL-26 09.14.47.667000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-53','ORD-001','PROD-B2',2,to_timestamp('02-JUL-26 09.14.47.681000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-54','ORD-001','PROD-A1',1,to_timestamp('02-JUL-26 09.16.37.978000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-55','ORD-001','PROD-B2',2,to_timestamp('02-JUL-26 09.16.37.987000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-56','ORD-001','PROD-B2',2,to_timestamp('02-JUL-26 09.17.07.539000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-57','ORD-001','PROD-A1',1,to_timestamp('03-JUL-26 06.40.23.444000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
Insert into INVENTORY_USER.INVENTORY_RESERVATIONS (RESERVATION_ID,ORDER_ID,PRODUCT_ID,QUANTITY,RESERVED_AT,STATUS) values ('RES-58','ORD-001','PROD-B2',1,to_timestamp('03-JUL-26 06.40.23.454000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'RESERVED');
REM INSERTING into INVENTORY_USER.PRODUCTS
SET DEFINE OFF;
Insert into INVENTORY_USER.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,UNIT_PRICE,CATEGORY,CREATED_AT) values ('PROD-A1','Laptop',999.99,'Electronics',to_timestamp('23-JUN-26 10.36.47.027000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INVENTORY_USER.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,UNIT_PRICE,CATEGORY,CREATED_AT) values ('PROD-B2','Wireless Mouse',29.99,'Accessories',to_timestamp('23-JUN-26 10.36.47.031000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INVENTORY_USER.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,UNIT_PRICE,CATEGORY,CREATED_AT) values ('PROD-C3','USB-C Hub',49.99,'Accessories',to_timestamp('23-JUN-26 10.36.47.034000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into INVENTORY_USER.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,UNIT_PRICE,CATEGORY,CREATED_AT) values ('PROD-D4','Monitor 27inch',399.99,'Electronics',to_timestamp('23-JUN-26 10.36.47.039000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
--------------------------------------------------------
--  DDL for Procedure UPDATE_INVENTORY_RESERVATION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "INVENTORY_USER"."UPDATE_INVENTORY_RESERVATION" (
    p_order_id      IN VARCHAR2,
    p_quantity      IN NUMBER,
    p_product_id    IN VARCHAR2,
    p_rows_affected OUT NUMBER
)
AS
BEGIN
    INSERT INTO INVENTORY_RESERVATIONS (
        RESERVATION_ID,
        ORDER_ID,
        PRODUCT_ID,
        QUANTITY,
        STATUS
    )
    SELECT 
        'RES-' || seq_reservation_id.NEXTVAL,
        p_order_id,
        PRODUCT_ID,
        p_quantity,
        'RESERVED'
    FROM VW_AVAILABLE_INVENTORY
    WHERE PRODUCT_ID = p_product_id
    AND AVAILABLE_QUANTITY >= p_quantity;

    p_rows_affected := SQL%ROWCOUNT;

    COMMIT;
END;

/
--------------------------------------------------------
--  Constraints for Table INVENTORY_RESERVATIONS
--------------------------------------------------------

  ALTER TABLE "INVENTORY_USER"."INVENTORY_RESERVATIONS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "INVENTORY_USER"."INVENTORY_RESERVATIONS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "INVENTORY_USER"."INVENTORY_RESERVATIONS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "INVENTORY_USER"."INVENTORY_RESERVATIONS" ADD CONSTRAINT "CHK_STATUS" CHECK (STATUS IN ('RESERVED','CONFIRMED','RELEASED')) ENABLE;
  ALTER TABLE "INVENTORY_USER"."INVENTORY_RESERVATIONS" ADD PRIMARY KEY ("RESERVATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "INVENTORY_USER"."PRODUCTS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "INVENTORY_USER"."PRODUCTS" MODIFY ("UNIT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "INVENTORY_USER"."PRODUCTS" ADD PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "INVENTORY_USER"."INVENTORY" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "INVENTORY_USER"."INVENTORY" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "INVENTORY_USER"."INVENTORY" ADD PRIMARY KEY ("INVENTORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "INVENTORY_USER"."INVENTORY" ADD CONSTRAINT "FK_INV_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "INVENTORY_USER"."PRODUCTS" ("PRODUCT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVENTORY_RESERVATIONS
--------------------------------------------------------

  ALTER TABLE "INVENTORY_USER"."INVENTORY_RESERVATIONS" ADD CONSTRAINT "FK_RES_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "INVENTORY_USER"."PRODUCTS" ("PRODUCT_ID") ENABLE;
